# ==============================================================================
# Setup Script: Internal Grok Coding Agent for Team (Windows PowerShell Edition)
# Repository: https://github.com/LyKhan77/grok-x-team-byLee.git
# ==============================================================================

#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$DEFAULT_LAN_ENDPOINT = "http://192.168.2.143:8001/v1"
$DEFAULT_LOCAL_ENDPOINT = "http://127.0.0.1:8001/v1"
$DEFAULT_MODEL_NAME = "qwen35"
$SCRIPT_DIR = Split-Path -Parent $MyInvocation.MyCommand.Path

Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "   🚀 Internal Grok Coding Agent Setup (Windows PowerShell) " -ForegroundColor Cyan
Write-Host "======================================================`n" -ForegroundColor Cyan

# 1. Deteksi / Install binary grok
if (Get-Command "grok" -ErrorAction SilentlyContinue) {
    Write-Host "✔ Grok CLI terdeteksi di sistem." -ForegroundColor Green
} else {
    Write-Host "Grok CLI belum terdeteksi di PATH." -ForegroundColor Yellow
    Write-Host "Mengunduh installer resmi xAI Grok untuk Windows..." -ForegroundColor Yellow
    try {
        Invoke-Expression (Invoke-RestMethod "https://x.ai/cli/install.ps1")
        $env:PATH += ";$env:USERPROFILE\.grok\bin;$env:LOCALAPPDATA\Programs\grok\bin"
    } catch {
        Write-Host "✖ Gagal mengunduh installer otomatis. Silakan pasang Grok CLI manual jika diperlukan." -ForegroundColor Red
    }
}

# 2. Pilihan Endpoint Server
Write-Host "`nPilih Endpoint AI Server Llama.cpp yang akan digunakan:"
Write-Host "  1) Jaringan LAN Kantor ($DEFAULT_LAN_ENDPOINT) [Rekomendasi Laptop/PC Tim]"
Write-Host "  2) Localhost Server ($DEFAULT_LOCAL_ENDPOINT) [Jika jalan langsung di server AI]"
Write-Host "  3) Custom Endpoint (IP / Domain / VPN / Cloudflare Tunnel)"
$choice = Read-Host "Pilihan [1/2/3, default: 1]"

if ([string]::IsNullOrWhiteSpace($choice) -or $choice -eq "1") {
    $SERVER_URL = $DEFAULT_LAN_ENDPOINT
} elseif ($choice -eq "2") {
    $SERVER_URL = $DEFAULT_LOCAL_ENDPOINT
} else {
    $custom = Read-Host "Masukkan URL Endpoint API (contoh: http://10.8.0.62:8001/v1)"
    if ([string]::IsNullOrWhiteSpace($custom)) {
        $SERVER_URL = $DEFAULT_LAN_ENDPOINT
    } else {
        $SERVER_URL = $custom
    }
}

# 3. Test Koneksi ke Server
$HEALTH_URL = $SERVER_URL.TrimEnd('/v1') + "/health"
Write-Host "`nMenguji koneksi ke: $HEALTH_URL..." -ForegroundColor Yellow

try {
    $response = Invoke-RestMethod -Uri $HEALTH_URL -TimeoutSec 5 -ErrorAction Stop
    if ($response.status -eq "ok" -or "$response" -match "ok") {
        Write-Host "✔ Koneksi Berhasil! Server llama.cpp aktif & sehat." -ForegroundColor Green
    } else {
        Write-Host "✔ Terhubung ke server." -ForegroundColor Green
    }
} catch {
    Write-Host "✖ Peringatan: Tidak dapat terhubung ke $HEALTH_URL." -ForegroundColor Red
    Write-Host "Pastikan Anda terhubung ke Wi-Fi kantor / VPN dan server AI sedang aktif." -ForegroundColor Yellow
}

# 4. Generate %USERPROFILE%\.grok\config.toml
$GROK_DIR = Join-Path $env:USERPROFILE ".grok"
if (-not (Test-Path $GROK_DIR)) {
    New-Item -ItemType Directory -Path $GROK_DIR -Force | Out-Null
}

$CONFIG_FILE = Join-Path $GROK_DIR "config.toml"
Write-Host "`nMenulis konfigurasi ke: $CONFIG_FILE..." -ForegroundColor Cyan

$configContent = @"
# Auto-generated by Internal Team Setup Script (Windows Edition)
[cli]
auto_update = false

[features]
telemetry = false

[session]
auto_compact_threshold_percent = 90    # Auto-compact saat context mencapai 90% (~118K tokens)
load_envrc = true

[models]
default = "internal-qwen"
stream_tool_calls = true
temperature = 0.7
top_p = 0.85
min_p = 0.05
repeat_penalty = 1.1
max_completion_tokens = 65536
max_tokens = 65536
max_output_tokens = 65536

[model.internal-qwen]
model = "$DEFAULT_MODEL_NAME"
base_url = "$SERVER_URL"
name = "Internal Qwen 3.8 (27B Q8 - 128K Dedicated)"
description = "Dedicated 128K Context with Auto-Compact 90% & Hybrid Sampling"
api_backend = "chat_completions"
context_window = 131072
max_completion_tokens = 65536
max_tokens = 65536
max_output_tokens = 65536
temperature = 0.7
top_p = 0.85
min_p = 0.05
repeat_penalty = 1.1
presence_penalty = 0.1
api_key = "sk-internal-team"
"@

[System.IO.File]::WriteAllText($CONFIG_FILE, $configContent, [System.Text.Encoding]::UTF8)

# 5. Pasang Git Hooks Otomatis (jika git diinisialisasi)
if (Test-Path (Join-Path $SCRIPT_DIR ".git")) {
    $hooksPath = (Join-Path $SCRIPT_DIR "scripts/hooks").Replace("\", "/")
    git config core.hooksPath "$hooksPath" 2>$null
    Write-Host "✔ Git pre-commit secret protection hooks diaktifkan." -ForegroundColor Green
}

# 6. Pasang grok-standardize shortcut untuk Windows
$LOCAL_BIN = Join-Path $env:USERPROFILE ".local\bin"
if (-not (Test-Path $LOCAL_BIN)) {
    New-Item -ItemType Directory -Path $LOCAL_BIN -Force | Out-Null
}

$standardizePy = Join-Path $SCRIPT_DIR "scripts\standardize.py"
$cmdWrapper = Join-Path $LOCAL_BIN "grok-standardize.cmd"
$ps1Wrapper = Join-Path $LOCAL_BIN "grok-standardize.ps1"

if (Test-Path $standardizePy) {
    "@echo off`npython `"$standardizePy`" %*" | Out-File -FilePath $cmdWrapper -Encoding ascii
    "& python `"$standardizePy`" `$args" | Out-File -FilePath $ps1Wrapper -Encoding utf8
    Write-Host "✔ Shortcut grok-standardize berhasil dipasang." -ForegroundColor Green
}

Write-Host "✔ Konfigurasi berhasil disimpan!`n" -ForegroundColor Green

Write-Host "======================================================" -ForegroundColor Cyan
Write-Host "🎉 Setup Selesai! Cara menggunakan Grok Agent di Windows:" -ForegroundColor Green
Write-Host "  1. Buka PowerShell / Terminal di folder project coding Anda."
Write-Host "  2. Jalankan perintah: grok"
Write-Host "  3. Model akan otomatis menggunakan [Internal Qwen 3.8 Dedicated 128K]."
Write-Host "  4. Tekan Ctrl + M untuk melihat atau mengganti model."
Write-Host "======================================================" -ForegroundColor Cyan
