#!/usr/bin/env bash
# ==============================================================================
# Setup Script: Internal Grok Coding Agent for Team
# Repository: https://github.com/LyKhan77/grok-x-team-byLee.git
# ==============================================================================
set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

DEFAULT_LAN_ENDPOINT="http://192.168.2.143:8001/v1"
DEFAULT_LOCAL_ENDPOINT="http://127.0.0.1:8001/v1"
DEFAULT_MODEL_NAME="qwen35"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

echo -e "${CYAN}======================================================${NC}"
echo -e "${CYAN}   🚀 Internal Grok Coding Agent Setup (Team Edition) ${NC}"
echo -e "${CYAN}======================================================${NC}\n"

# 1. Deteksi / Install binary grok
if command -v grok &> /dev/null; then
    echo -e "${GREEN}✔ Grok CLI terdeteksi:${NC} $(grok --version 2>/dev/null || echo 'Installed')"
else
    echo -e "${YELLOW}Grok CLI belum terpasang. Menginstall binary resmi...${NC}"
    curl -fsSL https://x.ai/cli/install.sh | bash
    export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"
fi

# 2. Pilihan Endpoint Server
echo -e "\nPilih Endpoint AI Server Llama.cpp yang akan digunakan:"
echo -e "  1) Jaringan LAN Kantor (${DEFAULT_LAN_ENDPOINT}) [Rekomendasi Laptop/PC Tim]"
echo -e "  2) Localhost Server (${DEFAULT_LOCAL_ENDPOINT}) [Jika jalan langsung di server AI]"
echo -e "  3) Custom Endpoint (IP / Domain / VPN / Cloudflare Tunnel)"
read -rp "Pilihan [1/2/3, default: 1]: " ENDPOINT_CHOICE

ENDPOINT_CHOICE=${ENDPOINT_CHOICE:-1}

if [ "$ENDPOINT_CHOICE" == "1" ]; then
    SERVER_URL="$DEFAULT_LAN_ENDPOINT"
elif [ "$ENDPOINT_CHOICE" == "2" ]; then
    SERVER_URL="$DEFAULT_LOCAL_ENDPOINT"
else
    read -rp "Masukkan URL Endpoint API (contoh: http://10.8.0.62:8001/v1): " SERVER_URL
    SERVER_URL=${SERVER_URL:-$DEFAULT_LAN_ENDPOINT}
fi

# 3. Test Koneksi ke Server
HEALTH_URL="${SERVER_URL%/v1}/health"
echo -e "\n${YELLOW}Menguji koneksi ke: ${HEALTH_URL}...${NC}"

if curl -s --connect-timeout 5 "$HEALTH_URL" | grep -q "ok"; then
    echo -e "${GREEN}✔ Koneksi Berhasil! Server llama.cpp aktif & sehat.${NC}"
else
    echo -e "${RED}✖ Peringatan: Tidak dapat terhubung ke ${HEALTH_URL}.${NC}"
    echo -e "${YELLOW}Pastikan Anda berada di jaringan Wi-Fi/VPN kantor atau server AI sedang aktif.${NC}"
fi

# 4. Generate ~/.grok/config.toml
mkdir -p "$HOME/.grok"
CONFIG_FILE="$HOME/.grok/config.toml"

echo -e "\nMenulis konfigurasi ke: ${CYAN}${CONFIG_FILE}${NC}..."

cat <<EOF > "$CONFIG_FILE"
# Auto-generated by Internal Team Setup Script
[cli]
auto_update = false

[features]
telemetry = false

[models]
default = "internal-qwen"
stream_tool_calls = true
temperature = 0.7
top_p = 0.95
max_completion_tokens = 8192

[model.internal-qwen]
model = "${DEFAULT_MODEL_NAME}"
base_url = "${SERVER_URL}"
name = "Internal Qwen 3.8 (27B Q8)"
description = "In-House Dedicated Coding Agent Model"
api_backend = "chat_completions"
context_window = 131072
temperature = 0.7
api_key = "sk-internal-team"
EOF

# 5. Pasang Git Hooks Otomatis (jika git diinisialisasi)
if [ -d "${SCRIPT_DIR}/.git" ]; then
    git config core.hooksPath "${SCRIPT_DIR}/scripts/hooks" 2>/dev/null || true
    echo -e "${GREEN}✔ Git pre-commit secret protection hooks diaktifkan.${NC}"
fi

# 6. Pasang command grok-standardize ke ~/.local/bin
mkdir -p "$HOME/.local/bin"
if [ -f "${SCRIPT_DIR}/scripts/standardize.py" ]; then
    ln -sf "${SCRIPT_DIR}/scripts/standardize.py" "$HOME/.local/bin/grok-standardize"
    chmod +x "$HOME/.local/bin/grok-standardize"
fi

echo -e "${GREEN}✔ Konfigurasi berhasil disimpan!${NC}\n"

echo -e "${CYAN}======================================================${NC}"
echo -e "${GREEN}🎉 Setup Selesai! Cara menggunakan Grok Agent:${NC}"
echo -e "  1. Buka terminal di folder project coding Anda."
echo -e "  2. Jalankan: ${CYAN}grok-standardize${NC} atau ketik ${YELLOW}/standardization${NC} di chat untuk menyusun aturan proyek."
echo -e "  3. Jalankan perintah: ${CYAN}grok${NC}"
echo -e "  4. Model akan otomatis menggunakan [Internal Qwen 3.8]."
echo -e "  5. Tekan ${YELLOW}Ctrl + M${NC} untuk melihat atau mengganti model."
echo -e "${CYAN}======================================================${NC}"
