#!/usr/bin/env bash
# ==============================================================================
# Setup Script: CooperAgent (CooperxHarness - Grok Build & Pi Agent)
# Platform: Linux & macOS Edition (Port 8987 Gateway & 256K Context)
# Repository: https://github.com/LyKhan77/grok-x-team-byLee.git
# ==============================================================================
set -e

GREEN='\033[0;32m'
CYAN='\033[0;36m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

DEFAULT_LAN_ENDPOINT="http://192.168.2.143:8987/api/v1"
DEFAULT_LOCAL_ENDPOINT="http://127.0.0.1:8987/api/v1"
DEFAULT_MODEL_NAME="qwen35"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OS_TYPE="$(uname -s)"

echo -e "${CYAN}================================================================${NC}"
echo -e "${CYAN}   🚀 CooperAgent Multi-Harness Onboarding (Linux & macOS)     ${NC}"
echo -e "${CYAN}================================================================${NC}\n"

# 1. Pilihan Coding Agent Harness
echo -e "${YELLOW}Pilih Coding Agent yang ingin dipasang/dikonfigurasi:${NC}"
echo -e "  1) Grok Build (Fullscreen Rust TUI, Visual Diff Viewer) [Rekomendasi Utama]"
echo -e "  2) Pi Agent (Lightweight Inline CLI Coding Agent) [Alternatif Ringan]"
echo -e "  3) Keduanya (Grok Build + Pi Agent)"
read -rp "Pilihan [1/2/3, default: 1]: " AGENT_CHOICE
AGENT_CHOICE=${AGENT_CHOICE:-1}

# 2. Input Identitas Developer
echo -e "\n${CYAN}--- Identitas Developer (CooperxTelemetry) ---${NC}"
read -rp "Masukkan nama/nickname Anda (contoh: lee, alex, budi, vincent) [default: dev-user]: " DEV_NAME
DEV_NAME=${DEV_NAME:-dev-user}
DEV_NAME=$(echo "$DEV_NAME" | tr '[:upper:]' '[:lower:]' | tr -cd 'a-z0-9_-')
[ -z "$DEV_NAME" ] && DEV_NAME="dev-user"
echo -e "${GREEN}✔ Identitas tersimpan:${NC} ${DEV_NAME}"

# 3. Pilihan Endpoint Server
echo -e "\n${CYAN}--- Endpoint CooperAgent AI Server ---${NC}"
echo -e "  1) Jaringan LAN Kantor (${DEFAULT_LAN_ENDPOINT}) [Rekomendasi Laptop/PC Tim]"
echo -e "  2) Localhost Server (${DEFAULT_LOCAL_ENDPOINT}) [Jika jalan langsung di server AI]"
echo -e "  3) Custom Endpoint (IP / Domain / VPN Tunnel)"
read -rp "Pilihan [1/2/3, default: 1]: " ENDPOINT_CHOICE
ENDPOINT_CHOICE=${ENDPOINT_CHOICE:-1}

if [ "$ENDPOINT_CHOICE" == "1" ]; then
    SERVER_URL="$DEFAULT_LAN_ENDPOINT"
elif [ "$ENDPOINT_CHOICE" == "2" ]; then
    SERVER_URL="$DEFAULT_LOCAL_ENDPOINT"
else
    read -rp "Masukkan URL Endpoint API (contoh: http://10.8.0.62:8987/api/v1): " SERVER_URL
    SERVER_URL=${SERVER_URL:-$DEFAULT_LAN_ENDPOINT}
fi

# 4. Test Koneksi ke Server (Health Check)
HEALTH_URL="${SERVER_URL%/api/v1}/api/health"
echo -e "\n${YELLOW}Menguji koneksi ke CooperAgent Gateway: ${HEALTH_URL}...${NC}"

if curl -s --connect-timeout 5 "$HEALTH_URL" | grep -q "ok"; then
    echo -e "${GREEN}✔ Koneksi Berhasil! CooperAgent Gateway & GPU Backend aktif & sehat.${NC}"
else
    echo -e "${RED}✖ Peringatan: Tidak dapat terhubung ke ${HEALTH_URL}.${NC}"
    echo -e "${YELLOW}Pastikan Anda berada di jaringan Wi-Fi/VPN kantor atau server AI sedang aktif.${NC}"
fi

# 5. Instalasi & Konfigurasi Grok Build (jika opsi 1 atau 3)
if [ "$AGENT_CHOICE" == "1" ] || [ "$AGENT_CHOICE" == "3" ]; then
    echo -e "\n${CYAN}--- Mengonfigurasi Grok Build (Rust TUI) ---${NC}"
    if command -v grok &> /dev/null; then
        echo -e "${GREEN}✔ Grok CLI terdeteksi:${NC} $(grok --version 2>/dev/null || echo 'Installed')"
    else
        echo -e "${YELLOW}Mengunduh binary Grok CLI resmi...${NC}"
        curl -fsSL https://x.ai/cli/install.sh | bash || true
        export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"

        if [ "$OS_TYPE" == "Darwin" ]; then
            [ -f "$HOME/.zshrc" ] && echo 'export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
            [ -f "$HOME/.bash_profile" ] && echo 'export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"' >> "$HOME/.bash_profile"
        else
            [ -f "$HOME/.bashrc" ] && echo 'export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"' >> "$HOME/.bashrc"
            [ -f "$HOME/.zshrc" ] && echo 'export PATH="$HOME/.grok/bin:$HOME/.local/bin:$PATH"' >> "$HOME/.zshrc"
        fi
    fi

    mkdir -p "$HOME/.grok"
    CONFIG_FILE="$HOME/.grok/config.toml"
    cat <<EOF > "$CONFIG_FILE"
# Auto-generated by CooperAgent Setup Script
[cli]
auto_update = false

[features]
telemetry = false

[session]
# auto_compact dinonaktifkan agar tidak ada jeda freeze, gunakan CooperxMemory handover
load_envrc = true

[models]
default = "internal-qwen"
stream_tool_calls = true
temperature = 1.0
top_p = 0.95
min_p = 0.0
repeat_penalty = 1.0
max_completion_tokens = 12288
max_tokens = 12288
max_output_tokens = 12288

[model.internal-qwen]
model = "${DEFAULT_MODEL_NAME}"
base_url = "${SERVER_URL}"
name = "CooperAgent Qwen 3.8 (27B Q8 - 168K Dedicated)"
description = "Dedicated 168K Dedicated Context Window via Port 8987 Gateway"
api_backend = "chat_completions"
context_window = 172032
max_completion_tokens = 12288
max_tokens = 12288
max_output_tokens = 12288
temperature = 1.0
top_p = 0.95
min_p = 0.0
repeat_penalty = 1.0
presence_penalty = 0.0
api_key = "dev-${DEV_NAME}"
EOF
    echo -e "${GREEN}✔ Konfigurasi Grok tersimpan di: ${CONFIG_FILE}${NC}"
fi

# 6. Konfigurasi Pi Agent (pi.dev) (jika opsi 2 atau 3)
if [ "$AGENT_CHOICE" == "2" ] || [ "$AGENT_CHOICE" == "3" ]; then
    echo -e "\n${CYAN}--- Mengonfigurasi Pi Agent (pi.dev) ---${NC}"
    
    # 1. Coba install official pi.dev package via npm jika npm tersedia
    if command -v npm &> /dev/null; then
        echo -e "${YELLOW}Memeriksa / Menginstall official Pi Agent (@earendil-works/pi-coding-agent)...${NC}"
        npm install -g --ignore-scripts @earendil-works/pi-coding-agent 2>/dev/null || true
    fi

    mkdir -p "$HOME/.pi/agent"
    
    cat <<EOF > "$HOME/.pi/agent/models.json"
{
  "providers": {
    "cooperagent": {
      "name": "CooperAgent In-House",
      "baseUrl": "${SERVER_URL%/api/v1}/v1",
      "api": "openai-completions",
      "apiKey": "dev-${DEV_NAME}",
      "models": [
        {
          "id": "${DEFAULT_MODEL_NAME}",
          "name": "CooperAgent Qwen 3.8 (27B Q8 - 168K)",
          "contextWindow": 172032,
          "maxTokens": 12288
        }
      ]
    }
  }
}
EOF

    cat <<EOF > "$HOME/.pi/agent/settings.json"
{
  "defaultModel": "cooperagent/${DEFAULT_MODEL_NAME}"
}
EOF

    echo -e "${GREEN}✔ Konfigurasi resmi pi.dev tersimpan di: $HOME/.pi/agent/models.json${NC}"
fi

# 7. Pasang Git Hooks Otomatis (jika git diinisialisasi)
if [ -d "${SCRIPT_DIR}/.git" ]; then
    git config core.hooksPath "${SCRIPT_DIR}/scripts/hooks" 2>/dev/null || true
    echo -e "${GREEN}✔ Git pre-commit secret protection hooks diaktifkan.${NC}"
fi

# 8. Pasang command standardize & pi ke ~/.local/bin
mkdir -p "$HOME/.local/bin"
if [ -f "${SCRIPT_DIR}/scripts/standardize.py" ]; then
    ln -sf "${SCRIPT_DIR}/scripts/standardize.py" "$HOME/.local/bin/cooper-standardize" 2>/dev/null || true
    ln -sf "${SCRIPT_DIR}/scripts/standardize.py" "$HOME/.local/bin/grok-standardize" 2>/dev/null || true
    chmod +x "${SCRIPT_DIR}/scripts/standardize.py"
fi
if [ -f "${SCRIPT_DIR}/scripts/pi_agent.py" ]; then
    ln -sf "${SCRIPT_DIR}/scripts/pi_agent.py" "$HOME/.local/bin/pi" 2>/dev/null || true
    chmod +x "${SCRIPT_DIR}/scripts/pi_agent.py"
fi

echo -e "\n${CYAN}================================================================${NC}"
echo -e "${GREEN}🎉 Setup Selesai! Selamat datang di CooperAgent!${NC}"
echo -e "  - Menjalankan Grok Build: Ketik ${CYAN}grok${NC} di folder project Anda."
echo -e "  - Menjalankan Pi Agent:   Ketik ${CYAN}pi${NC} di folder project Anda."
echo -e "  - Standarisasi Project:  Ketik ${CYAN}cooper-standardize${NC} atau ${YELLOW}/standardization${NC}."
echo -e "  - Persistensi Memori:    Gunakan ${CYAN}CooperxMemory${NC} (.agents/memory/session_state.md)."
echo -e "  - Pantau Dashboard:      Buka ${CYAN}http://192.168.2.143:8987/${NC}"
echo -e "${CYAN}================================================================${NC}\n"
