#!/usr/bin/env python3
"""
Adaptive Project Standardization Wizard
Interactive questionnaire that auto-detects tech stack and generates tailored
.agents/rules/ for the current workspace.
Can be invoked manually or via slash command /standardization.
"""

import argparse
import json
import os
import sys
from datetime import datetime
from pathlib import Path

CYAN = "\033[0;36m"
GREEN = "\033[0;32m"
YELLOW = "\033[1;33m"
BLUE = "\033[0;34m"
RED = "\033[0;31m"
BOLD = "\033[1m"
NC = "\033[0m"


def auto_detect_stack(root_path: Path) -> dict:
    """Detects technologies present in the workspace."""
    detected = []
    default_lang = "General / Polyglot"
    default_test = "Pytest / Standard Unit Testing"
    default_linter = "Standard Linters & Formatters"

    if (root_path / "Cargo.toml").exists():
        detected.append("Rust (Cargo.toml detected)")
        default_lang = "Rust"
        default_test = "Cargo test (Built-in Rust unit/integration tests)"
        default_linter = "Cargo clippy & rustfmt"

    if any((root_path / f).exists() for f in ["pyproject.toml", "requirements.txt", "Pipfile", "setup.py"]):
        detected.append("Python (pyproject.toml/requirements.txt detected)")
        if default_lang == "General / Polyglot":
            default_lang = "Python"
            default_test = "Pytest with AsyncIO support"
            default_linter = "Ruff / Black & MyPy typing"

    if (root_path / "package.json").exists():
        detected.append("TypeScript / JavaScript (package.json detected)")
        if default_lang == "General / Polyglot":
            default_lang = "TypeScript"
            default_test = "Vitest / Jest"
            default_linter = "ESLint & Prettier"

    if (root_path / "go.mod").exists():
        detected.append("Go (go.mod detected)")
        if default_lang == "General / Polyglot":
            default_lang = "Go"
            default_test = "go test ./..."
            default_linter = "golangci-lint"

    return {
        "detected_list": detected,
        "default_lang": default_lang,
        "default_test": default_test,
        "default_linter": default_linter,
    }


def prompt_choice(question: str, options: list, default_idx: int = 0, auto: bool = False) -> str:
    """Displays a prompt with enumerated choices."""
    if auto:
        return options[default_idx]

    print(f"\n{BOLD}{CYAN}? {question}{NC}")
    for i, opt in enumerate(options, 1):
        marker = f"{GREEN}(Default){NC}" if (i - 1) == default_idx else ""
        print(f"  {BOLD}{i}){NC} {opt} {marker}")

    while True:
        try:
            choice = input(f"{YELLOW}Pilihan [1-{len(options)}, default: {default_idx + 1}]: {NC}").strip()
            if not choice:
                return options[default_idx]
            idx = int(choice) - 1
            if 0 <= idx < len(options):
                return options[idx]
            print(f"{RED}Nomor pilihan tidak valid. Masukkan 1-{len(options)}.{NC}")
        except (ValueError, KeyboardInterrupt):
            print(f"\n{YELLOW}Menggunakan pilihan default: {options[default_idx]}{NC}")
            return options[default_idx]


def generate_rules(target_dir: Path, answers: dict):
    """Generates clean Markdown rules under .agents/rules/."""
    rules_dir = target_dir / ".agents" / "rules"
    rules_dir.mkdir(parents=True, exist_ok=True)
    now_str = datetime.now().strftime("%Y-%m-%d")

    # 00-project-context.md
    (rules_dir / "00-project-context.md").write_text(f"""# Project Context & Architecture Standard
# Generated by Adaptive Standardization Wizard on {now_str}

## Primary Tech Stack
- **Primary Language / Ecosystem:** {answers['lang']}
- **Project Scope:** Internal Team Enterprise Component
- **Inference & Agent Environment:** 100% On-Premise Llama.cpp Qwen 27B Backend

## Core Engineering Principles
1. **YAGNI & Minimal Complexity:** Never introduce speculative abstractions or unneeded dependencies. Standard library and native constructs come first.
2. **Deterministic & Isolated Architecture:** Clear modular boundaries with single responsibilities per module.
3. **Continuous Changelog:** Every meaningful modification to the codebase must be recorded in `CHANGELOG.md`.
""", encoding="utf-8")

    # 01-coding-standards.md
    (rules_dir / "01-coding-standards.md").write_text(f"""# Coding & Code Quality Standards

## Linters & Formatting
- **Configured Linters / Formatters:** {answers['linter']}
- Code must be formatted and lint-clean prior to committing.
- Avoid suppressed warnings (`# noqa`, `#[allow(...)]`, `@ts-ignore`) unless documented with specific rationale.

## Code Design Guidelines
- **Explicit over Implicit:** Explicit typing, clear function signatures, and unambiguous naming.
- **Error Handling:** Never swallow exceptions or discard errors silently. Every error path must return actionable diagnostics.
""", encoding="utf-8")

    # 02-git-workflow.md
    (rules_dir / "02-git-workflow.md").write_text(f"""# Git Workflow & Commit Conventions

## Commit Format Standard: {answers['commit']}
- **Conventional Commits Format:**
  - `feat:` for new features or capabilities.
  - `fix:` for bug fixes.
  - `refactor:` for code restructuring without behavior changes.
  - `perf:` for performance optimizations.
  - `test:` for test additions or updates.
  - `docs:` for documentation updates.
  - `chore:` for tooling, dependencies, or configuration changes.

## Branching & Atomic Commits
- Branches must follow `feature/<name>`, `bugfix/<name>`, or `hotfix/<name>`.
- Commits must be atomic, buildable, and self-contained.
""", encoding="utf-8")

    # 03-testing-guidelines.md
    (rules_dir / "03-testing-guidelines.md").write_text(f"""# Testing Strategy & QA Standards

## Test Framework: {answers['test']}
## Testing Protocol: {answers['tdd']}
- **Test-First Verification:** Write or update tests before or alongside implementation.
- **Isolated Unit Testing:** Unit tests must execute quickly and use mocks/stubs for external network or hardware dependencies.
- **Regression Prevention:** Every bug fix must include a test demonstrating the failure before the fix and passing after.
""", encoding="utf-8")

    # 04-security-privacy.md
    (rules_dir / "04-security-privacy.md").write_text(f"""# Security, Secrets & Privacy Guardrails

## Data Privacy Policy: {answers['security']}
- **Zero Secrets in Codebase:** Absolutely no API keys, private tokens, passwords, or credentials committed to git. Use `.env` variables.
- **Data Sovereignty:** No telemetry, internal project source code, or customer context may be dispatched to public cloud endpoints.
- **Input Validation & Sanitization:** Validate and sanitize all external inputs, shell arguments, and file paths.
""", encoding="utf-8")

    # Mark as standardized
    meta_file = target_dir / ".agents" / ".standardized.json"
    meta_file.write_text(json.dumps({
        "initialized_at": now_str,
        "answers": answers,
    }, indent=2), encoding="utf-8")


def register_trusted_directory(target_dir: Path):
    """Saves directory to ~/.grok/trusted_dirs.json."""
    config_dir = Path.home() / ".grok"
    config_dir.mkdir(parents=True, exist_ok=True)
    trusted_file = config_dir / "trusted_dirs.json"

    data = {"trusted_paths": []}
    if trusted_file.exists():
        try:
            data = json.loads(trusted_file.read_text(encoding="utf-8"))
        except Exception:
            data = {"trusted_paths": []}

    path_str = str(target_dir.resolve())
    if path_str not in data.get("trusted_paths", []):
        data["trusted_paths"].append(path_str)
        trusted_file.write_text(json.dumps(data, indent=2), encoding="utf-8")


def main():
    parser = argparse.ArgumentParser(description="Adaptive Project Standardization Wizard")
    parser.add_argument("--dir", default=".", help="Target project root directory")
    parser.add_argument("--auto", action="store_true", help="Auto-accept detected defaults without prompting")
    parser.add_argument("--force", action="store_true", help="Force re-run standardization even if already initialized")
    args = parser.parse_args()

    target_dir = Path(args.dir).resolve()
    meta_file = target_dir / ".agents" / ".standardized.json"

    print(f"\n{BOLD}{CYAN}================================================================={NC}")
    print(f"{BOLD}{CYAN}  🧙 Adaptive Project Standardization Wizard (/standardization)  {NC}")
    print(f"{BOLD}{CYAN}================================================================={NC}")
    print(f"Target Directory: {BOLD}{target_dir}{NC}\n")

    if meta_file.exists() and not args.force and not args.auto:
        print(f"{GREEN}✔ Direktori ini sudah terstandarisasi sebelumnya (.agents/rules/ aktif).{NC}")
        re_run = input(f"{YELLOW}Apakah ingin mengonfigurasi ulang aturan proyek? [y/N]: {NC}").strip().lower()
        if re_run != "y":
            print(f"{BLUE}Menggunakan aturan standarisasi yang sudah ada.{NC}\n")
            return

    # 1. Auto-detection
    stack = auto_detect_stack(target_dir)
    if stack["detected_list"]:
        print(f"{GREEN}✔ Deteksi otomatis menemukan artefak proyek:{NC}")
        for item in stack["detected_list"]:
            print(f"   • {item}")
    else:
        print(f"{YELLOW}ℹ Tidak ditemukan manifest bahasa khusus, menggunakan profil Polyglot.{NC}")

    # 2. Interactive Questions
    lang_opts = [
        stack["default_lang"],
        "Rust (Cargo / High-Performance Systems)",
        "Python (FastAPI / Async / AI Engine)",
        "TypeScript / JavaScript (Node / Frontend / Fullstack)",
        "Go (Microservices / Tooling)",
        "Polyglot / Multi-Language",
    ]
    # Deduplicate while preserving order
    lang_opts = list(dict.fromkeys(lang_opts))
    selected_lang = prompt_choice("1. Apa bahasa pemrograman / tech stack utama proyek ini?", lang_opts, 0, args.auto)

    test_opts = [
        stack["default_test"],
        "Pytest (Python Async / Parametrized Testing)",
        "Cargo test (Rust Unit & Integration Suite)",
        "Vitest / Jest (TypeScript / JavaScript)",
        "Go testing framework",
        "Pragmatic Unit & Integration Tests",
    ]
    test_opts = list(dict.fromkeys(test_opts))
    selected_test = prompt_choice("2. Apa framework pengujian (testing framework) yang digunakan?", test_opts, 0, args.auto)

    tdd_opts = [
        "TDD-Strict: Wajib membuat/mengupdate test sebelum/bersama implementasi kode",
        "Pragmatic QA: Unit test wajib untuk logika inti & perbaikan bug",
        "Regression-Only: Test untuk mencegah regresi pada critical path",
    ]
    selected_tdd = prompt_choice("3. Apa strategi & metodologi pengujian yang diinginkan?", tdd_opts, 0, args.auto)

    commit_opts = [
        "Conventional Commits (feat:, fix:, refactor:, test:, docs:, chore:)",
        "Ticket-Prefix (e.g. [PROJ-123] feat: description)",
        "Descriptive Git Commits (Clear capitalized summaries)",
    ]
    selected_commit = prompt_choice("4. Apa standar format pesan Git Commit tim?", commit_opts, 0, args.auto)

    linter_opts = [
        stack["default_linter"],
        "Ruff, Black, & MyPy (Python)",
        "Clippy & rustfmt (Rust)",
        "ESLint & Prettier (TypeScript/JavaScript)",
        "golangci-lint (Go)",
        "Standard Clean Code Guidelines",
    ]
    linter_opts = list(dict.fromkeys(linter_opts))
    selected_linter = prompt_choice("5. Linter dan code style formatter apa yang digunakan?", linter_opts, 0, args.auto)

    security_opts = [
        "Strict Enterprise: 100% On-Premise, zero external cloud telemetry, anti-secret scanning",
        "Standard Team Privacy: No secrets in repo, internal API primary",
    ]
    selected_security = prompt_choice("6. Tingkat keamanan & privasi data proyek:", security_opts, 0, args.auto)

    answers = {
        "lang": selected_lang,
        "test": selected_test,
        "tdd": selected_tdd,
        "commit": selected_commit,
        "linter": selected_linter,
        "security": selected_security,
    }

    # 3. Generate rules & register
    print(f"\n{YELLOW}Menyusun file standarisasi di .agents/rules/...{NC}")
    generate_rules(target_dir, answers)
    register_trusted_directory(target_dir)

    print(f"{GREEN}✔ Standarisasi Proyek Berhasil Dibuat!{NC}")
    print(f"  📁 File aturan: {BOLD}.agents/rules/{NC}")
    print(f"     • 00-project-context.md")
    print(f"     • 01-coding-standards.md")
    print(f"     • 02-git-workflow.md")
    print(f"     • 03-testing-guidelines.md")
    print(f"     • 04-security-privacy.md")
    print(f"  🔒 Direktori telah ditandai sebagai: {BOLD}Trusted Project{NC}\n")


if __name__ == "__main__":
    main()
